domain_path: /home/brage/embedded/z7nano/CPU/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/brage/.local/share/vivado/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
