# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ps/ps.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps || ORIG_REF_NAME==ps} -quiet] -quiet

# IP: bd/ps/ip/ps_processing_system7_0_0/ps_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_processing_system7_0_0 || ORIG_REF_NAME==ps_processing_system7_0_0} -quiet] -quiet

# XDC: /home/brage/embedded/z7nano/FPGA/platform/platform.gen/sources_1/bd/ps/ps_ooc.xdc
